### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Qwebeck#2]
Hey @Qwebeck 
It seems that you've forgot to commit some css files:
![image](https://cloud.githubusercontent.com/assets/25591824/23283827/ce492d5c-fa30-11e6-8eec-0a624cdadcce.png)

Please commit them and push into repository, so I can run your website !

Here is example how does your website look like https://artinov.github.io/home-work-7-Qwebeck/

**Comment by Qwebeck** [comment]
Fixed

**Comment by eko24ive** [comment]
Nice !
